#!/usr/bin/env node
/**
 * fetch-fonts.js
 * ---------------------------------------------------------------------------
 * Downloads the three typefaces the guide uses and writes a local @font-face
 * sheet, so the page never calls out to Google Fonts. Together with
 * fetch-images.js this makes the whole site work with no network at all.
 *
 *   node scripts/fetch-fonts.js
 * ---------------------------------------------------------------------------
 */

'use strict';

const fs = require('fs');
const path = require('path');

const OUT_DIR = path.join(__dirname, '..', 'public', 'fonts');
const CSS_OUT = path.join(OUT_DIR, 'fonts.css');

// A modern UA is what makes Google answer with woff2 rather than ttf.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

const HREF =
  'https://fonts.googleapis.com/css2' +
  '?family=Fraunces:opsz,wght@9..144,400;9..144,600;9..144,700;9..144,900' +
  '&family=Inter:wght@400;500;600;700' +
  '&family=JetBrains+Mono:wght@400;500' +
  '&display=swap';

const fileNameFor = (url) => {
  const base = url.split('/').slice(-2).join('-').replace(/[^A-Za-z0-9._-]/g, '');
  return base.endsWith('.woff2') ? base : `${base}.woff2`;
};

(async () => {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const css = await (await fetch(HREF, { headers: { 'User-Agent': UA } })).text();
  const urls = [...new Set([...css.matchAll(/url\((https:\/\/[^)]+)\)/g)].map((m) => m[1]))];
  console.log(`${urls.length} font files\n`);

  let bytes = 0;
  let local = css;

  for (const url of urls) {
    const name = fileNameFor(url);
    const buffer = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    fs.writeFileSync(path.join(OUT_DIR, name), buffer);
    bytes += buffer.length;
    local = local.split(url).join(`/fonts/${name}`);
    console.log(`  ${name} (${(buffer.length / 1024).toFixed(0)} kB)`);
  }

  fs.writeFileSync(
    CSS_OUT,
    `/* Generated by scripts/fetch-fonts.js — do not edit by hand. */\n${local}`
  );

  console.log(`\n  ${(bytes / 1e6).toFixed(2)} MB → public/fonts/`);
  console.log(`  sheet → public/fonts/fonts.css\n`);
})();
